### ISSUE TITLE
[Docs] Initialize Readme with project description

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-smp-action#2]
**Current State:**
Template content in the readme.

**Desired State:**
Project-specific content in the readme.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@s1ntaxe770r?

**Comment by josephmidura** [comment]
Before I overthink this issue, is the desired outcome just text from the Meshery documentation? My brain was swimming when I looked at this before.

**Comment by leecalcote** [comment]
Great question. Yes, more or less. This repository is to contain a GitHub Action for purposes of making it convenient for people integrate Meshery's performance characterization capabilities into their pipelines (into their GitHub workflows). 

This SMP-focused Action is something of a sibling action to that of https://github.com/layer5io/meshery-smi-conformance-action, which is for purposed of running conformance tests to verify compliance with the SMI spec using Meshery in your workflow.

This SMP-focused Action will run performance test based on the Performance Profile you provide (more or less as described here - https://docs.meshery.io/functionality/performance-management).

If you're at all inclined, please do your worst, @josephmidura.

**Comment by leecalcote** [comment]
Inclusion of the GetNighthawk logo is ideal.

**Comment by navendu-pottekkat** [comment]
The current readme is pretty thorough and covers everything about the project for a user to use just the readme to get started.

**Comment by leecalcote** [comment]
Yes, it really is. This issue was overlooked at the time that you wrote that update. Closing...
