### ISSUE TITLE
Update the dynamic test name in the scheduled workflow

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery-smp-action#21]
#### Current Behavior

The Scheduled Benchmark Tests workflow creates dynamic test names based on the configuration of the test. Current format is shown below.

https://github.com/layer5io/meshery-smp-action/blob/b999f0aec563c79590a640050e8d691315116582/.github/workflows/scheduled-benchmarks.yml#L59

So, a sample test name now is: `istio-fortio-load-test.yaml`

#### Desired Behavior

Remove the `.yaml` from the test name and only include the rest of the file name.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by navendu-pottekkat** [comment]
Possible solution: https://stackoverflow.com/questions/4168371/how-can-i-remove-all-text-after-a-character-in-bash

**Comment by varunsaral** [comment]
Please assign me this

**Comment by navendu-pottekkat** [comment]
Sure. Here you go.

**Comment by piyushsingariya** [comment]
Hey @varunsaral checking in if you're still working on this??

**Comment by varunsaral** [comment]
yes @piyushsingariya i'm working on it , we can connect on slack if you want to discuss about it.

**Comment by piyushsingariya** [comment]
Sure, I'm excited to see some work on this.

**Comment by gyohuangxin** [comment]
I will implement this in my PR about scheduled benchmark on self-hosted runner.

**Comment by gyohuangxin** [comment]
PR merged, close it.
