### ISSUE TITLE
Run scheduled benchmarks on different sample applications

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery-smp-action#33]
#### Current Behavior

Currently the tests are run with the sample application of the particular service mesh. This is different for each service mesh.

#### Desired Behavior

Add sample application as a configurable item and run tests across multiple applications for each service mesh.

A new field should be [added here](https://github.com/layer5io/meshery-smp-action/blob/2f296c567ae53696d8c578bdd9bf517a7a916a83/.github/workflows/scheduled-benchmarks.yml#L68) and the scripts needs to be changed to take in this dynamic value.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by navendu-pottekkat** [comment]
Issue opened from a discussion on comments https://github.com/layer5io/meshery-smp-action/issues/27#issuecomment-991036158 and https://github.com/layer5io/meshery-smp-action/issues/27#issuecomment-991082219

**Comment by gyohuangxin** [comment]
@navendu-pottekkat Thank you!

**Comment by navendu-pottekkat** [comment]
We do have sample applications within Meshery but those functionalities aren't available in the CLI yet. We are working on a design specification to add those features.

We do want to use `mesheryctl` to deploy sample apps if we can or we can come back later and change the script to use `mesheryctl`.

`mesheryctl app onboard file.yaml` should work here.

Here is the [list of sample apps](https://docs.meshery.io/guides/sample-apps) we use currently.

**Comment by navendu-pottekkat** [comment]
But for now, we can start with Bookinfo and Emojivoto from Istio and Linkerd. These scripts are already present.

**Comment by navendu-pottekkat** [comment]
Great question. We added indefinite tokens just recently for this use case within CI/CD. Let me share the details over Slack.

**Comment by leecalcote** [comment]
@asubedy, up for this?

**Comment by asubedy** [comment]
Yes I will try to work on this.

Before starting @navendu-pottekkat wanted to make few things clear:
So we are trying to check performance of the application say for example `bookinfo` deployed on other service mesh too like Linkerd and osm and not just on Istio. So for this we need to edit the current scripts of each service mesh to accommodate these different/dynamic application test.

Please correct me if I am wrong.

**Comment by leecalcote** [comment]
@asubedy yes, that's right.

**Comment by asubedy** [comment]
Yes ok I'll try this.
