### ISSUE TITLE
Add newcomers-alert.yml and slack.yml [Docs]

### ISSUE THREAD

**Issue by FidalMathew** [layer5io/meshery-smp-action#34]
**Current State:**

No newcomers-alert.yml
Out of date slack.yml

**Desired State:**

Updated newcomers-alert.yml and slack.yml

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by FidalMathew** [comment]
I would like to work on this issue :)

**Comment by warunicorn19** [comment]
Go ahead @FidalMathew
