### ISSUE TITLE
Make the self-hosted runner configurable as the workflow's options

### ISSUE THREAD

**Issue by gyohuangxin** [layer5io/meshery-smp-action#41]
#### Current Behavior

We had an implementation of running SMP on self-hosted runner #39 , but the configuration of self-hosted runner is hardcoded as "c3.small.x86". 

#### Desired Behavior

We should make self-hosted runner configurable as the workflow's options, e.g. server type, location......

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
Is this still an open need?

**Comment by gyohuangxin** [comment]
@leecalcote  I think yes, this issue is to make machine type can be configurable rather than hardcoding as "c3.small.x86".
@hershd23 If you're around, can you look at this?

**Comment by leecalcote** [comment]
Thank you for reopening.
