### ISSUE TITLE
[Self hosted] Keep track of machine state to minimise waiting time

### ISSUE THREAD

**Issue by hershd23** [layer5io/meshery-smp-action#42]
#### Current Behavior

Currently we are arbitrarily waiting 10 minutes waiting for the server to get provisioned and started.

https://github.com/layer5io/meshery-smp-action/blob/20c0b6f64f4918c6ad2505810210e0480a409648/.github/workflows/scripts/start-cil-runner.sh#L27 

#### Desired Behavior

We want to optimise on our waiting time by keeping track of the state variable by the machine

#### Implementation

The logic of this can look like

- If "state" == "provisioning", sleep 10s...
- If "state" == "active", echo "Machine successfully created!" and continue.
- If "state" == "failed", echo "Failed to create machine" and exit.

in the above mentioned bash script.

A little experimentation might be required based on the intervals on which we poll. (We do not want cause anything that might come under a DOS attack :) )
#### Acceptance Tests

A link to the self-hosted workflow run would be key to get your changes accepted

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by gyohuangxin** [comment]
Thank you for opening this issue and it's good to be thoughtful about time intervals. Can you look into this?
