### ISSUE TITLE
Cherry-pick self-hosted commit to master branch

### ISSUE THREAD

**Issue by gyohuangxin** [layer5io/meshery-smp-action#44]
Regarding https://github.com/layer5io/meshery-smp-action/issues/38, we have implement running SMP on self-hosted CNCF cluster, and codes have been merged into self-hosted branch. We should cherry-pick it to master branch. 

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
Makes sense. 👌
