### ISSUE TITLE
Enable other service meshes performance tests 

### ISSUE THREAD

**Issue by gyohuangxin** [layer5io/meshery-smp-action#51]
#### Current Behavior

We have included Istio, Linkerd, OSM performance tests.

#### Desired Behavior

We should enable other service meshes performance tests listed on https://smp-spec.io/dashboard.

- [ ] Consul
- [ ] App Mesh
- [ ] Kuma
- [ ] Cilium

#### Implementation

Writing bash scripts for each mesh is time consuming, so we should use `mesheryctl` to deploy them.
And we should use `mesheryctl app onboard` to deploy sample apps if https://github.com/layer5io/meshery-smp-action/pull/48 is readay.

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by gyohuangxin** [comment]
@leecalcote Does it work to use `mesheryctl` to deploy above meshes now? 
@hershd23 I will appreciate it if you can do me a favor on this.

**Comment by leecalcote** [comment]
Tagging @piyushsingariya @hexxdump @gr455 to speak to this first question. _It should._

**Comment by gyohuangxin** [comment]
Is `mesheryctl app onboard` ready for sample applications of above meshes? Where is their yaml files?
