### ISSUE TITLE
Rename the profiles of performance tests

### ISSUE THREAD

**Issue by gyohuangxin** [layer5io/meshery-smp-action#59]
#### Current Behavior

Performance test profiles are named as {service-mesh}-{load-generator}-{test-configuration}.yaml currently, it‘s ugly and hard to understand.
![image](https://user-images.githubusercontent.com/42127654/182509445-f2aa6a3e-88bc-46ce-929b-113a1b1233fa.png)

The goal of this issue is to discuss and find out the how to make the profile names be in order for people to understand what is being tested.

**Comment by gyohuangxin** [comment]
@leecalcote @hershd23

**Comment by leecalcote** [comment]
Perfect. @asubedy is here to assist.

**Comment by hershd23** [comment]
It is ugly, but it has sort of complete information about the test as it just `-` separates all the parameters.

In the new naming construct. Do we want this information in the title or some kind of metadata? Maybe we can also add the added detail whether it was the GitHub runner or personal hardware

**Comment by gyohuangxin** [comment]
@hershd23 Yes, it's just ugly but its information is enough. We can rename this profile name with human readable text, like `Istio Soak Test with Fortio`, but it‘s also fine if still using `-`. 
@leecalcote What do you think?

**Comment by gyohuangxin** [comment]
@asubedy Yes, it's a good idea. Where does the subtext come from? How can we put information here?

**Comment by asubedy** [comment]
@gyohuangxin Right now the subtext is hardcoded.

**Comment by hershd23** [comment]
Sure @asubedy @gyohuangxin let's go with the runner type in the subtext. As far as the main performance test goes, trying to make it a coherent English sentence and `-` separating stuff doesn't seem different at all to me.

Are we fixated on the Title-Subtitle format @asubedy or can we just specify a UUID type identifier for the test and list the configurations on the card, like service mesh - istio. Test - load test and so on with the datetime of test completion?

**Comment by asubedy** [comment]
@hershd23 I think having a title on the card is necessary. Other details can be listed as you said.

**Comment by hershd23** [comment]
Hi did we come to any conclusions here?

**Comment by gyohuangxin** [comment]
Great! As details can be listed in the subcontext, we can list current informations as below:

### Istio Load Test with Forito
Service mesh: Istio
Load generator: Fortio
Test configuration: Load test
Date:  Aug 10 21:39:33 CST 2022

**Comment by gyohuangxin** [comment]
@hershd23 @asubedy What do you think?

**Comment by asubedy** [comment]
@gyohuangxin yes this looks good. Just one change, simply date does not explain lots of things, maybe Date updated or date created something that is relevant

**Comment by gyohuangxin** [comment]
@asubedy Great, thanks for your suggestion. BTW, can we get the benchmark start time and end time currently?

**Comment by gyohuangxin** [comment]
@hershd23 Can you raise a PR to change the profiles' names?
