### ISSUE TITLE
Benchmarks fails sometimes due to `mesheryctl pattern apply` error

### ISSUE THREAD

**Issue by gyohuangxin** [layer5io/meshery-smp-action#64]
#### Description

We use `mesheryctl patter apply` to deploy applications and manifests on Istio mesh, but it fails sometimes, even though we increased the sleep time: https://github.com/layer5io/meshery-smp-action/runs/8251690332?check_suite_focus=true#step:5:44

#### Environment:
- Meshery Version: 
- Kubernetes Version: 
- Host OS:
- Browser:

**Comment by gyohuangxin** [comment]
cc h@alphaX86 @hershd23

**Comment by alphaX86** [comment]
@gyohuangxin this bug occurs on self-hosted runners I assume? Because, I double checked by running the action on Configurable and scheduled ones and they worked fine; I don't have access to CNCF CIL cluster, so I couldn't check them

**Comment by gyohuangxin** [comment]
@alphaX86 I think it occurs both on github runners and self-hosted runners.
This is the error log when running on github runners: https://github.com/layer5io/meshery-smp-action/runs/8261567731?check_suite_focus=true#step:4:52

**Comment by hershd23** [comment]
```
Get "http://localhost:32639/api/system/sync": dial tcp [::1]:32639: connect: connection refused
Onboarding application... Standby for few minutes...
Error: Post "http://localhost:32639/api/pattern": dial tcp [::1]:32639: connect: connection refused
Error from server (NotFound): namespaces "istio-system" not found
Error from server (NotFound): namespaces "istio-system" not found
Service Mesh: Istio - ISTIO
Gateway URL: http://192.168.[49](https://github.com/layer5io/meshery-smp-action/runs/8261567731?check_suite_focus=true#step:4:50).2:
```

Does this problem due to the fact that it is not connected to the meshery server or does this translate some k8s command independent of Meshery? @leecalcote @alphaX86 @gyohuangxin 

I'll try and check myself, but it would be faster is someone who knows this can explain or link me to the correct files in meshery

**Comment by gyohuangxin** [comment]
@hershd23 I have no more opinions on this issue, please go ahead. I think it's the best way to create issue in Meshery repo if you can reproduce it.
