### ISSUE TITLE
Mark test servers for auto-deletion using "end_at" parameter

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-smp-action#75]
### Current Behavior
Of the [scheduled tests](https://github.com/layer5io/meshery-smp-action/actions) that run multiple times a day, they have faced a few challenges. Notably, one of those challenges is in the cleanup phase once a test is complete. Currently, it is frequently the case that any number of bare metal servers that are used for testing or orphaned, and not decommissioned at the end of each test. This leaves an inordinate amount of bare metal servers, unnecessarily unavailable for used by other projects. 

@vielmetti has been most helpful in identifying ways to mitigate this from happening.

### Desired Behavior
All resources provisioned for a scheduled test are subsequently decommissioned at the end of that same test.

#### Implementation
Recently @vielmetti point this out:

> You can create servers that will auto-delete themselves at a time certain, perfect for test runs. See <https://deploy.equinix.com/developers/docs/metal/deploy/spot-market/#spot-market-request-creation>. You want the “end_at” parameter on the API endpoint for device creation

[Slack Message](https://layer5io.slack.com/archives/C011VPREG2Z/p1683843695620109)

### Acceptance Tests
1. Test servers are decommissioned at end of scheduled testing period.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by vielmetti** [comment]
looks like it's here that needs to be changed, and @gyohuangxin had the last edit. (actually looks like a pretty simple fix). We'll need to compute a timestamp.

[.github/workflows/scripts/start-cil-runner.sh](https://github.com/layer5io/meshery-smp-action/blob/862c5283953f1b5a3a607c9e1f00461f98a4b4d5/.github/workflows/scripts/start-cil-runner.sh#L20)

What I don't know is, how long are the tests expected to run, at worst case? Can the machines be clobbered in 24, 6, 2 hours?

**Comment by gyohuangxin** [comment]
@vielmetti  Currently, it runs in 30mins, at worst case. But considering that we may add more test cases in the future, I think 2 hours is a appropriate deadline.

**Comment by vielmetti** [comment]
@gyohuangxin The Equinix system bills by the hour, so my recommendation is to set the expiry at say 1 hour 50 minutes from the time it's created, that will catch anything relatively fast but not risk running 2:01 and incurring the extra charge.

The example end_at time is in ISO format, e.g

    "end_at": "2020-09-24T05:00:00Z",

which can be generated with something like `date -v +110M -Iminutes` .

**Comment by gyohuangxin** [comment]
@vielmetti I create a PR to fix this: https://github.com/layer5io/meshery-smp-action/pull/76/files, but I want to confirm the default time zone used by the Equinix system: 
https://github.com/layer5io/meshery-smp-action/pull/76/files#diff-0e9a22dd7a8bbc870d2ab77c5392deb500a1f946d0e6ff615d75792a2cd8e977R20

**Comment by gyohuangxin** [comment]
@vielmetti I confirmed that Equinix system is using UTC/GMT timezone, so please review the PR, thanks.
![image](https://github.com/layer5io/meshery-smp-action/assets/42127654/6802bee7-d972-47dc-a829-91bffc9e0826)

**Comment by vielmetti** [comment]
Thanks @gyohuangxin - I am checking on the semantics of "termination_time", to see if this is expected to work for ordinary instances or only for "spot instances". Will follow up soonest when I can confirm.

**Comment by vielmetti** [comment]
To complete this -

We have updated the Equinox Metal "termination_time" docs at https://deploy.equinix.com/developers/api/metal/#tag/Devices/operation/createDevice to reflect better the use case (ephemeral instances) and to document the time zone question described above.

Since this change was deployed last month we have not had any of the previous issues described! That's all good news.
