### ISSUE TITLE
Add sample performance test 

### ISSUE THREAD

**Issue by DelusionalOptimist** [layer5io/meshery-smp-action#8]
**Description**
Provide a sample performance test which would be done using this action so that users can consider what runner types and benchmark configurations should be used in other tests.

**Comment by navendu-pottekkat** [comment]
@DelusionalOptimist FYI, as we start using this action, we need to capture these and document these as well: https://github.com/layer5io/meshery-smp-action/issues/9

**Comment by navendu-pottekkat** [comment]
This issue is fixed. We do provide sample configurations here: https://github.com/layer5io/meshery-smp-action/blob/master/.github/load-test.yaml
