### ISSUE TITLE
Issue Template Updates for Figma link 

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/meshery-smp-action#80]
### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

### Desired Situation
Each template that has a reference to Figma in its resources section should an invite link added.

### Implementation 
```
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```

**Acceptance Tests**
All references to Figma include the "open invite" link.

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by depleur** [comment]
Hey, I'm down to work on this.

**Comment by Yana-Gupta** [comment]
@thisiskaransgit , I would like to work on this

**Comment by thisiskaransgit** [comment]
since @depleur, is assigned another issue, @Yana-Gupta please go ahead with this one, since we are missing other items, kindly add them too in the issue template
```
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

- 📚 See [contributing instructions](docs.meshery.io/contributing).
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).
```
