### ISSUE TITLE
Update minikube and kubernetes to latest versions

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-smp-action#84]
#### Current Behavior
These versions are highlighted in the readme as being used by the action currently:

```
          minikube version: 'v1.21.0'
          kubernetes version: 'v1.20.7'
```

#### Desired Behavior
The latest versions of these tools are:

```
          minikube version: 'v1.30.1'
          kubernetes version: 'v1.27.3'
```

#### Implementation
1. Use the latest versions in the action by default.
1. Update the scheduled tests to use the latest versions.

#### Acceptance Tests
1. New version of this GitHub Action is published to the marketplace.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Debjyoti0404** [comment]
Hey @leecalcote, I want to work on this issue. Can you assign me?

**Comment by Debjyoti0404** [comment]
**Previous:**
![image](https://github.com/layer5io/meshery-smp-action/assets/103656712/de127056-693a-4d0c-bd83-a858643c5f8b)

**Latest:**
![image](https://github.com/layer5io/meshery-smp-action/assets/103656712/fb1ea97a-fe83-4cbf-8878-995fa61dc6b1)

**Comment by Debjyoti0404** [comment]
> **Previous:** ![image](https://user-images.githubusercontent.com/103656712/253793483-de127056-693a-4d0c-bd83-a858643c5f8b.png)
> 
> **Latest:** ![image](https://user-images.githubusercontent.com/103656712/253793530-fb1ea97a-fe83-4cbf-8878-995fa61dc6b1.png)

If you allow me to go forward then I will raise a PR @leecalcote.

**Comment by Savio629** [comment]
There you go @Debjyoti0404
